# Generated by Django 4.2.7 on 2023-12-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivito',
            name='archivo_fisico',
            field=models.FileField(default=None, upload_to='archivitos/'),
            preserve_default=False,
        ),
    ]
